# Generated by Django 4.0.3 on 2024-02-08 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('it_pk', models.AutoField(primary_key=True, serialize=False)),
                ('it_title', models.CharField(max_length=10, null=True)),
                ('it_type', models.CharField(max_length=10, null=True)),
                ('tier', models.CharField(max_length=10, null=True)),
                ('tier_1', models.CharField(max_length=10, null=True)),
                ('tier_2', models.CharField(max_length=10, null=True)),
                ('tier_3', models.CharField(max_length=10, null=True)),
                ('tier_4', models.CharField(max_length=10, null=True)),
                ('tier_5', models.CharField(max_length=10, null=True)),
                ('tier_6', models.CharField(max_length=10, null=True)),
                ('tier_7', models.CharField(max_length=10, null=True)),
                ('tier_8', models.CharField(max_length=10, null=True)),
                ('tier_9', models.CharField(max_length=10, null=True)),
                ('tier_10', models.CharField(max_length=10, null=True)),
                ('level', models.IntegerField(default=0)),
                ('is_use', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'item_type',
            },
        ),
        migrations.CreateModel(
            name='WeaponData',
            fields=[
                ('wd_pk', models.AutoField(primary_key=True, serialize=False)),
                ('tier', models.IntegerField(null=True)),
                ('wd_type', models.CharField(max_length=20, null=True)),
                ('min_dam', models.IntegerField(default=0)),
                ('max_dam', models.IntegerField(default=0)),
                ('dam_increase', models.IntegerField(default=0)),
                ('buff_up', models.IntegerField(default=0)),
                ('time_extension', models.IntegerField(default=0)),
                ('consumption_reduction', models.IntegerField(default=0)),
                ('hit', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('mp', models.IntegerField(default=0)),
                ('sp', models.IntegerField(default=0)),
                ('str', models.IntegerField(default=0)),
                ('dex', models.IntegerField(default=0)),
                ('con', models.IntegerField(default=0)),
                ('wis', models.IntegerField(default=0)),
                ('int', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=0)),
                ('att_speed', models.IntegerField(default=0)),
                ('job', models.CharField(max_length=20, null=True)),
                ('is_use', models.IntegerField(default=1)),
                ('special_effects', models.JSONField(null=True)),
                ('it_pk', models.ForeignKey(db_column='it_pk', on_delete=django.db.models.deletion.CASCADE, to='asfo.itemtype')),
            ],
            options={
                'db_table': 'weapon_data',
            },
        ),
    ]
